theme: Vinay Kumar Kuresi Tutorials
title: Data Structures and Full Stack development
description: The idea behind the development of this tutorial is to reach every user who want to learn Software development. Feel free to update the content, by writing a pull request to me.
